character = Character.create([
    {
        role: "Netrunner",
        name: "RedEyes",
        background: "Street Rat, born in Upper Eastside nightcity, one hit of the net and she began her life as a hacker, surfing the world of digital warfare",
        motivation: "Lost her mother to a Corpo Mogul, everything is focused on revenge, no matter how sweet",
        goals: "To become the greatest edgerunner on the netscape",
        friends: "Torch, Johnny Silverhand, Varis",
        enemies: "Alistar Copperfield the Corpo who killed her mother",
        romance: "Never known love, lives her live in the digital space, finding physical people to be repulsive",
        personality: "Picky, fussy and nervous",
    },
    {
        role: "Nomad",
        name: "Max",
        background: "In a Nomad Pack moving from town to town, Family status in danger, he risks losing everything; family exiled or otherwise driven from their original home",
        motivation: "People are untrustworthy. Don't depend on anyone",
        goals: "He has to find his family, whats left of them",
        friends: "Roger Racer - his childhood pal",
        enemies: "Everyone",
        romance: "Kira, a girl he met in Japantown",
        personality: "Rebellious, antisocial, violent",
    },
    {
        role: "Media",
        name: "Clark Cooper",
        background: "Corporate Executives, both parents are living but work hard under the pressure of a megacorp",
        motivation: "Expose the truth",
        goals: "Find the criminal underworkings of the megacorps in the central city, and expose them to the world",
        friends: "Mitchel Pierce, Booker Merrell, Diana Sedlock",
        enemies: "Wencke Mable - Current CFO of Militech",
        romance: "Corey Usher, newscaster with Nightcity Radio",
        personality: "Friendly and outgoing",
    },

])

stats = Stat.create([
    {
        intelligence: 6,
        reflex: 8,
        dexterity: 6,
        technology: 5,
        cool: 9,
        willpower: 8,
        luck: 6,
        movement: 6,
        body: 10,
        empathy: 6,
        character_id: 1,
    },
    {
        intelligence: 6,
        reflex: 9,
        dexterity: 6,
        technology: 8,
        cool: 10,
        willpower: 6,
        luck: 6,
        movement: 8,
        body: 6,
        empathy: 5,
        character_id: 4,
    },
    {
        intelligence: 6,
        reflex: 8,
        dexterity: 6,
        technology: 9,
        cool: 6,
        willpower: 6,
        luck: 6,
        movement: 10,
        body: 8,
        empathy: 6,
        character_id: 3,
    }
])
