const LOAD_CHARACTERS = 'LOAD_CHARACTERS';
const SAVE_CHARACTER = 'SAVE_CHARACTER';
const LOAD_CHARACTER = 'LOAD_CHARACTER';
const UPDATE_CHARACTER = 'UPDATE_CHARACTER';

export {
    LOAD_CHARACTERS,
    SAVE_CHARACTER,
    LOAD_CHARACTER,
    UPDATE_CHARACTER
}